// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbhcaoaujjqqylcfwzao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiaGNhb2F1ampxcXlsY2Z3emFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzg2MTUsImV4cCI6MjA2OTU1NDYxNX0.XiXXU5mVPpWVXF2_teStGevc27uQjUxysUN5iib-dic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});